---
name: Amendment
description: Amend the Aragon Network Charter
title: "[Amendment]: "
labels: ["enhancement"]
assignees:
  - Michael-A-Heuer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make an amendment!
  - type: dropdown
    id: where
    attributes:
      label: In which part?
      description: In which part of the document would you like to make an amendment?
      options:
        - Introduction to the Charter
        - Aragon Network DAO Agreement
        - Aragon Manifesto
        - Community-Guidelines
        - Aragon Governance Proposal Process
        - Sub-DAO Agreements
        - Main DAO and Sub-DAO Parameters
        - Multiple parts
    validations:
      required: true
  - type: input
    id: where-precisely
    attributes:
      label: Where precisely?
      description: On which page and in which paragraph/line do you want to make an amendment?
      placeholder: ex. page 16, paragraph 5.g.i.2 to 4
    validations:
      required: false
  - type: textarea
    id: what
    attributes:
      label: What should be changed?
      description: What would you like to change (and how should it be formatted)?
      placeholder: ex. Add "XYZ".  Remove "ABC".  Replace "123" by "456".
    validations:
      required: true
---
