---
name: Correction
description: Correct an error you've spotted
title: "[Correction]: "
labels: ["error"]
assignees:
  - Michael-A-Heuer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this error report!
  - type: dropdown
    id: where
    attributes:
      label: In which part?
      description: In which part of the document did you find an error?
      options:
        - Introduction to the Charter
        - Aragon Network DAO Agreement
        - Aragon Manifesto
        - Community-Guidelines
        - Aragon Governance Proposal Process
        - Sub-DAO Agreements
        - Main DAO and Sub-DAO Parameters
    validations:
      required: true
  - type: input
    id: where-precisely
    attributes:
      label: Where precisely?
      description: On which page and in which paragraph/line is the error located?
      placeholder: ex. page 16, paragraph 5.g.i.2
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What is wrong?
      description: What is the error and how should it be corrected?
      placeholder: Tell us what's wrong!
    validations:
      required: true
---